controllers:
    resource: '../src/Controller/'
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

home:
    path: /
    controller: App\Controller\DefaultController::index
config-rh:
    path: /config-rh
    controller: App\Controller\DefaultController::config
front:
    path: /front
    controller: App\Controller\FrontController::index

contrat:
    path: /contrat
    controller: App\Controller\ContratController::index
employe:
        path: /employe
        controller: App\Controller\EmployeController::index
departement:
    path: /departement
    controller: App\Controller\DepartementController::index
type-conge:
    path: /ca/type/
    controller: App\Controller\CaTypeController::index
demande-conge:
    path: /ca/conge
    controller: App\Controller\CaCongeController::index
demande-conge-avalider:
    path: /ca/conge_avalider
    controller: App\Controller\CaCongeController::congesavalider
bulletin-paie:
    path: /bulletin
    controller: App\Controller\RhBulletinPaieController::index
struture-salaire:
    path: /struture
    controller: App\Controller\RhstructuresalaireController::index
advance-salaire:
    path: /advance
    controller: App\Controller\AdvanceSalaireController::index
categorie-regle:
    path: /categorie
    controller: App\Controller\RhCategorieRegleController::index
regle-salaire:
    path: /regle
    controller: App\Controller\RhreglesalaireController::index
mes-demande-conge:
    path: /ca/myconge
    controller: App\Controller\CaCongeController::myconge
presence:
    path: /presence
    controller: App\Controller\PresenceController::index
interface-presence:
    path: /interface-presence
    controller: App\Controller\PresenceController::interface
posterest:
    path: /posterest
    controller: App\Controller\EmployeController::listpost
    methods:  GET
employe_departementrest:
    path: /employedepartementrest
    controller: App\Controller\PresenceController::listsemploye
    methods:  GET
presencepostrest:
    path: /presencepostrest
    controller: App\Controller\PresenceController::postrest
    methods:  GET
presencegetdepartementrest:
    path: /presencegetdepartementrest
    controller: App\Controller\PresenceController::listspresence
    methods:  GET
congerest:
    path: /congerest
    controller: App\Controller\CaCongeController::update
    methods:  GET
conge_update_dayrest:
    path: /conge_update_dayrest
    controller: App\Controller\CaCongeController::updateNumberDay
    methods:  GET
reglerest:
    path: /reglerest
    controller: App\Controller\RhreglesalaireController::getJsonRegle
    methods:  GET
structurepostrest:
    path: /structurepost
    controller: App\Controller\RhstructuresalaireController::postJsonStructure
    methods:  GET
structurelinepostrest:
    path: /structurelinepost
    controller: App\Controller\RhlignereglestructureController::postJsonStructureLine
    methods:  GET
advancepostrest:
    path: /advancepostrest
    controller: App\Controller\AdvanceSalaireController::postJsonAdvance
    methods:  GET
advance_cheancepostrest:
    path: /advance_echeancepostrest
    controller: App\Controller\AdvanceSalaireEcheanceController::postJsonAdvanceEcheance
    methods:  GET
fos_user_security:
    prefix: /{_locale}
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_registration:
    prefix: /{_locale}/register
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"

fos_user_resetting:
    prefix: /{_locale}/resetting
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

fos_user_profile:
    prefix: /{_locale}/profile
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /{_locale}/group
calendar:
    resource: "@CalendarBundle/Resources/config/routing.yaml"
